# Generated by Django 6.0.6 on 2026-07-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ready_made', 'Ready-Made Receipt'), ('custom_stl', 'Custom STL Model'), ('custom_builder', 'Custom Builder')], db_index=True, max_length=20)),
                ('price_base_czk', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_large_czk', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('magnets_price_czk', models.DecimalField(decimal_places=2, default=49, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('template_type', models.CharField(blank=True, choices=[('wedding', 'Wedding Anniversary'), ('breakup', 'Breakup'), ('dating', 'Start of Dating'), ('dog', 'Getting a Dog'), ('friends', 'Becoming Friends')], max_length=20, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
