# Generated by Django 5.2.12 on 2026-07-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_seed_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('receipt_plaque', 'Účtenková plaketa'), ('music_plaque', 'Hudební plaketa'), ('soundwave_plaque', 'Zvuková vlna'), ('gps_plaque', 'Souřadnice')], db_index=True, default='receipt_plaque', help_text='Determines which customizer/preview/pricing logic is used.', max_length=30),
        ),
    ]
